### ISSUE TITLE
FYI: go mod issues

### ISSUE THREAD

**Issue by hsyed** [friendsofgo/errors#2]
```
go get -u github.com/friendsofgo/errors
go: downloading github.com/friendsofgo/errors v0.9.1
verifying github.com/friendsofgo/errors@v0.9.1: checksum mismatch
	downloaded: h1:ksGIdtObXKKxxMq9VgsjKecdLCOlXwsE6XypldOuDi0=
	sum.golang.org: h1:VnyCwEgi1BgGL4wAfCxBOLsSNyJ+iAwJOxh4Gbq7aI4=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

**Comment by hsyed** [comment]
was there a force push on the v0.9.1 tag by any chance ?

**Comment by hsyed** [comment]
@aperezg could you publish a new tag `v0.9.2` by any chance ?

**Comment by zikaeroh** [comment]
For now I have worked around this with:

```
exclude github.com/friendsofgo/errors v0.9.1
```

Followed by just grabbing the repo at master, since the only changes since 0.9.1 have been README updates.

Very disappointing to have force pushed... :(

**Comment by hsyed** [comment]
I can't use that work around for our scenario.The problem is we do production builds with Bazel and `rules_go` builds each external package in isolation. As each external package is built in isolation they try to fetch the latest version of the package (or whatever is listed in the go.mod). There is currently no way to alter this behaviour.

**Comment by aperezg** [comment]
Sorry for inconvenience guys! I've already published a new version https://github.com/friendsofgo/errors/releases/tag/v0.9.2 , let me know if all ok for you!

**Comment by zikaeroh** [comment]
The new tag makes the sum database happy. Thanks.
